---
- name: Request certificate (first time - this can take a long time)
  command:
    cmd: >
      certbot certonly --agree-tos --email {{ ssl_cert_email }} --non-interactive
          --preferred-challenges=dns --non-interactive
          --manual --manual-auth-hook {{ homeserver_path }}/certificate/authenticator.sh
          --manual-cleanup-hook {{ homeserver_path }}/certificate/cleanup.sh
          -d homeserver.gamesmith.uk -d '*.{{ server_domain }}' -v {{ certbot_extra_args }}
    creates: "/etc/letsencrypt/live/{{ server_domain }}/fullchain.pem"
  environment:
    HOSTED_ZONE: "{{ route53_hosted_zone }} "

- name: Add certificate renewal to crontab
  cron:
    name: "Renew certificate"
    job: "/usr/bin/certbot renew --quiet"
