---
- name: Install basic system
  hosts: all
  become: yes

  vars_files:
    - variables.yml

  tasks:

    - name: Update keys
      shell: pacman-key --populate > ~/.pacman-key
      args:
        creates: ~/.pacman-key

    - name: Full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      pacman:
        name: [
          'unzip', 'sudo', 'vim', 'wget', 'iwd', 'dhcpcd', 'bash-completion', 'man-db',
          'man-pages', 'tmux', 'git', 'gcc', 'mlocate', 'dnsutils', 'htop', 'lsof',
          'inetutils', 'mc', 'base-devel', 'jq', 'tree', 'vi'
        ]
        state: present

    - name: Create sudoers group
      group:
        name: wheel
        state: present

    - name: Create admin user
      user:
        name: "{{ admin_user }}"
        groups: users,wheel
        append: yes
        createhome: yes
        # ssh_key_file
        password: "{{ admin_password }}"

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Install AUR packages
      kewlfft.aur.aur:
        name: [ 'aws-cli-v2-bin', 'yay-bin' ]
        use: makepkg
        state: present
      become_user: "{{ admin_user }}"

    - name: Install AUR packages
      kewlfft.aur.aur:
        upgrade: yes
        use: yay
        aur_only: yes
      become_user: "{{ admin_user }}"

    - name: Create .ssh directory
      file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ admin_user }}"
      become_user: "{{ admin_user }}"

    - name: Configure private SSH key
      copy:
        src: "{{ ssh_private_key_file }}"
        dest: "/home/{{ admin_user }}/.ssh/home-network.key"
        owner: "{{ admin_user }}"
        mode: '0600'
      become_user: "{{ admin_user }}"

    # TODO - create ssh keys
    # TODO - configure admin user (dotfiles, remove useless dirs)
    # TODO - get git contrib file from internet
