---
- name: Create a base install
  hosts: all

  vars_files:
    - variables.yml

  tasks:

    - name: Update keys
      become: yes
      shell: pacman-key --populate > ~/.pacman-key
      args:
        creates: ~/.pacman-key

    - name: Full system upgrade
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      become: yes
      pacman:
        name: [ 'unzip', 'sudo', 'vim' ]
        state: present

    - name: Create sudoers group
      become: yes
      group:
        name: sudoers
        state: present

    - name: Create admin user
      become: yes
      user:
        name: "{{ admin_user }}"
        groups: users,sudoers
        append: yes
        # ssh_key_file
        password: "{{ admin_password }}"
