---
- name: Install basic system
  hosts: all
  become: yes

  vars_files:
    - variables.yml

  tasks:

    - name: Update keys
      shell: pacman-key --populate > ~/.pacman-key
      args:
        creates: ~/.pacman-key

    - name: Full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      pacman:
        name: [
          'unzip', 'sudo', 'vim', 'wget', 'iwd', 'dhcpcd', 'bash-completion', 'man-db',
          'man-pages', 'tmux', 'git', 'gcc', 'mlocate', 'dnsutils', 'htop', 'lsof',
          'inetutils', 'mc', 'base-devel', 'jq', 'tree', 'vi', 'ansible'
        ]
        state: present

    - name: Create sudoers group
      group:
        name: wheel
        state: present

    - name: Create admin user
      user:
        name: "{{ admin_user }}"
        groups: users,wheel
        append: yes
        createhome: yes
        # ssh_key_file
        password: "{{ admin_password }}"

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Install AUR packages
      kewlfft.aur.aur:
        name: [ 'aws-cli-v2-bin', 'yay-bin' ]
        use: makepkg
        state: present
      become_user: "{{ admin_user }}"

    - name: Update AUR packages
      kewlfft.aur.aur:
        upgrade: yes
        use: yay
        aur_only: yes
      become_user: "{{ admin_user }}"

    - name: Create .ssh directory
      file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ admin_user }}"
      become_user: "{{ admin_user }}"

    - name: Install public SSH key
      copy:
        src: "{{ ssh_public_key_file }}"
        dest: "/home/{{ admin_user }}/.ssh/authorized_keys"
        owner: "{{ admin_user }}"
        mode: '0600'
      become_user: "{{ admin_user }}"

    - name: Install private SSH key to connect to other servers
      copy:
        src: "{{ ssh_private_key_file }}"
        dest: "/home/{{ admin_user }}/.ssh/home-ansible.key"
        owner: "{{ admin_user }}"
        mode: '0600'
      become_user: "{{ admin_user }}"

    - name: Create ssh config file
      copy:
        content: ""
        dest: "/home/{{ admin_user }}/.ssh/config"
        force: no
        owner: "{{ admin_user }}"
        mode: '0600'
      become_user: "{{ admin_user }}"

    - name: Configure hosts in ssh config file
      blockinfile:
        dest: "/home/{{ admin_user }}/.ssh/config"
        content: |
          HOST {{ item }}
            HostName {{ item }}.wagner
            Port 22
            User {{ admin_user }}
            IdentityFile ~/.ssh/home-ansible.key
        marker_begin: "BEGIN {{ item }}"
      with_items: [ 'homeserver', 'wagner', 'pizero', 'retropi', 'terminal' ]  # TODO - put this somewhere?

    - name: Clone home-ansible repostitory
      git:
        repo: "https://{{ git_username }}:{{ git_password }}@github.com/andrenho/home-ansible.git"
        dest: ~/src/home-ansible
      become_user: "{{ admin_user }}"

    # TODO - configure admin user (dotfiles, remove useless dirs)
    # TODO - get git contrib file from internet
