---

# TODO - services
#   - ftp
#   - sftp
#   - dynamicdns, backup
#   - mqtt, dnla
#   - nginx (partial), pihole
#   - homer (configure yaml file)
#   - dokuwiki, portainer, openbooks
#   - ssh, explorer
#   - sonarr, radarr, bazarr
#   - cyberchef, audioserve, hoppscotch
#   - rss, rss-db
#   - ubooquity, podgrab
#   - torrent
#   - plex
#   - dev


# TODO - create password files (nginx, sftp, etc)
# TODO - configure docker compose
# TODO - install dash and install/start service
# TODO - create docker service and install/start service
