- name: Clone dotfiles repository
  git:
    repo: "https://{{ git_username }}:{{ git_password }}@github.com/andrenho/.dotfiles.git"
    dest: ~/src/dotfiles/
  become_user: "{{ admin_user }}"

- name: Copy dotfiles to home (user)
  copy:
    src: "~/src/dotfiles/{{ item }}"
    remote_src: true
    dest: "~"
  become_user: "{{ admin_user }}"
  with_items: "{{ dotfiles }}"

- name: Copy dotfiles to home (root)
  copy:
    src: "/home/{{ admin_user }}/src/dotfiles/{{ item }}"
    remote_src: true
    dest: "/root/"
  with_items: "{{ dotfiles }}"

- name: Create neofetch config dir
  file:
    path: "/home/{{ admin_user }}/.config/neofetch"
    state: directory

- name: Copy neofetch config file
  copy:
    src: "/home/{{ admin_user }}/src/dotfiles/.neofetch.conf"
    remote_src: true
    dest: "/home/{{ admin_user }}/.config/neofetch/config"
  become_user: "{{ admin_user }}"

- name: Create gitprompt directory
  file:
    path: "{{ gitprompt_path }}"
    state: directory

- name: Download and install gitprompt file
  get_url:
    url: "{{ gitprompt_url }}"
    dest: "{{ gitprompt_path }}/git-prompt.sh"

- name: Create .gitconfig file
  template:
    src: files/gitconfig
    dest: ~/.gitconfig
  become_user: "{{ admin_user }}"
