- name: Create sudoers group
  group:
    name: wheel
    state: present

- name: Create admin user
  user:
    name: "{{ admin_user }}"
    groups: users,wheel
    append: yes
    createhome: yes
    password: "{{ admin_password | string | password_hash('sha512', admin_password_salt | string) }}"
    uid: "{{ admin_uid }}"

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
