- name: Create data group
  group:
    name: data
    state: present
    gid: "{{ data_gid }}"

- name: Create data user
  user:
    name: data
    group: data
    create_home: no
    uid: "{{ data_uid }}"
    shell: "/usr/bin/false"
    password: "!"

- name: Create sudoers group
  group:
    name: wheel
    state: present

- name: Create admin user
  user:
    name: "{{ admin_user }}"
    groups: users,wheel,data
    append: yes
    createhome: yes
    password: "{{ admin_password | string | password_hash('sha512', admin_password_salt | string) }}"
    uid: "{{ admin_uid }}"

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
