---

- name: Get list of block devices
  shell: "lsblk -lno NAME | grep '^{{ data_device }}$'"
  register: lsblk
  when: data_device is defined
  ignore_errors: true

- name: Fail if data device does not exist
  fail:
    msg: "/dev/{{ data_device }} does not exist"
  when: data_device is defined and lsblk.rc != 0

- name: Mount data device
  mount:
    path: "{{ data_mount_point }}"
    src: "/dev/{{ data_device }}"
    fstype: ext4
    opts: defaults,lazytime,user,exec
    state: mounted
  when: data_device is defined

- name: Restore backup from file   # TODO - check if it was not already restored
  copy:
    src: "{{ restore_file }}"
    dest: /tmp/backup
  when: restore_from == 'file'

# TODO - restore from S3

- name: Uncompress backup
  unarchive:
    remote_src: true
    src: /tmp/backup
    dest: "{{ data_mount_point }}/"
  when: restore_from == 'file' or restore_from == 's3'

- name: Remove backup file
  file:
    path: /tmp/backup
    state: absent
