# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_EXPERIMENTAL"] = "disks"

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  config.vm.network "private_network", ip: "192.168.56.2"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.disk :disk, size: "500MB", name: "extra_storage"

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true

    # v.customize ['createhd', '--filename', 'data.vdi', '--size', 500 * 1024]
    # v.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'data.vdi']
  end

end
