# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_EXPERIMENTAL"] = "disks"

$script = <<-SCRIPT
pacman -Sy --noconfirm parted
parted -s -a optimal /dev/sdb mklabel gpt -- mkpart primary ext4 1 499MB
mkfs.ext4 /dev/sdb1
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  config.vm.network "private_network", ip: "192.168.56.2"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.disk :disk, size: "500MB", name: "extra_storage"

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  config.vm.provision "shell", inline: $script

end
