---
- name: Install and configure GUI for admin
  hosts: admin-gui
  become: yes

  tasks:
    - name: Install server admin GUI packages (void)
      xbps:
        name: "{{ item }}"
        state: latest
      with_items: "{{ admin_gui_void_packages }}"
      when: ansible_distribution == 'void'

    - name: Install dwm
      include_role:
        name: admingui-dwm

    - name: Copy wallpaper
      copy:
        src: "files/wallpaper/{{ ansible_nodename }}.jpg"
        dest: "/usr/local/share/misc/wallpaper.jpg"
        mode: "0644"
        force: no

    - name: Setup lightdm config file
      copy:
        src: files/config/lightdm-gtk-greeter.conf
        dest: /etc/lightdm/

    - name: Install fonts
      include_role:
        name: admingui-fonts

    - name: Install alacritty config file
      copy:
        src: files/config/alacritty.yml
        dest: "/home/{{ admin_user }}/.alacritty.yml"
      become_user: "{{ admin_user }}"

    - name: Add user to group audio
      user:
        name: "{{ admin_user }}"
        groups: ['audio', 'bluetooth']
        append: yes

    - name: Enable dbus service
      service:
        name: dbus
        enabled: true

          #    - name: Enable lightdm service
          #      service:
          #        name: lightdm
          #        enabled: true

    - name: Enable bluetooth service
      service:
        name: bluetoothd
        enabled: true

    - name: Configure Window Maker
      include_role:
        name: admingui-wmaker
