---
- name: Install basic system
  hosts: all
  become: yes

  tasks:

    - name: Create admin & data users
      include_role:
        name: base-admin-user

    - name: Install base packages (Arch)
      include_role:
        name: base-packages-arch
      when: ansible_distribution == 'Archlinux'

    - name: Install base packages (Void)
      include_role:
        name: base-packages-void
      when: ansible_distribution == 'void'

    - name: Install base packages (Debian)
      include_role:
        name: base-packages-debian
      when: ansible_distribution == 'Debian'

    - name: Configure SSH
      include_role:
        name: base-ssh-config

    - name: Install dotfiles for admin & root
      include_role:
        name: base-dotfiles

    - name: Clone home-ansible repository
      git:
        repo: "https://{{ git_username }}:{{ git_password }}@github.com/andrenho/home-ansible.git"
        dest: ~/src/home-ansible
      become_user: "{{ admin_user }}"
