---
- name: Install basic system
  hosts: all
  become: yes

  tasks:

    - name: Create admin user
      include_role:
        name: base-admin-user

    - name: Install base packages
      include_role:
        name: base-packages

    - name: Configure SSH
      include_role:
        name: base-ssh-config

    - name: Clone home-ansible repostitory
      git:
        repo: "https://{{ git_username }}:{{ git_password }}@github.com/andrenho/home-ansible.git"
        dest: ~/src/home-ansible
      become_user: "{{ admin_user }}"

    # TODO - configure admin user (dotfiles, remove useless dirs)
    # TODO - get git contrib file from internet
