---
- name: Install basic system
  hosts: all
  become: yes

  tasks:

    - name: Create admin user
      include_role:
        name: base-admin-user

    - name: Install base packages
      include_role:
        name: base-packages

    - name: Configure SSH
      include_role:
        name: base-ssh-config

    - name: Install dotfiles for admin
      include_role:
        name: base-dotfiles

    - name: Clone home-ansible repository
      git:
        repo: "https://{{ git_username }}:{{ git_password }}@github.com/andrenho/home-ansible.git"
        dest: ~/src/home-ansible
      become_user: "{{ admin_user }}"

    # TODO - create .gitconfig
