---
- name: Install and configure server
  hosts: server
  become: yes

  tasks:

    - name: Install server packages
      include_role:
        name: server-packages

    - name: Setup docker server
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add admin to group docker
      user:
        name: "{{ admin_user }}"
        groups: docker
        append: yes

    - name: Create AWS credentials
      include_role:
        name: server-aws-creds

    - name: Clone homeserver repository
      git:
        repo: "https://{{ git_username }}:{{ git_password }}@github.com/andrenho/homeserver.git"
        dest: "{{ homeserver_path }}"

    - name: Request certificate
      command:
        cmd: >
          certbot certonly --agree-tos --email {{ ssl_cert_email }}
              --preferred-challenges=dns --non-interactive
              --manual --manual-auth-hook {{ homeserver_path }}/certificate/authenticator.sh
              --manual-cleanup-hook {{ homeserver_path }}/certificate/cleanup.sh
              -d homeserver.gamesmith.uk -d '*.{{ server_domain }}' -v {{ certbot_extra_args }}
        creates: "/etc/letsencrypt/live/{{ server_domain }}/fullchain.pem"

# TODO - restore backup
# TODO - clone homeserver
# TODO - create password files (nginx, sftp, etc)
# TODO - configure docker compose
# TODO - mount external disk
# TODO - install dash and install/start service
# TODO - create docker service and install/start service
