---
- name: iptables-nft is installed?
  command: pacman -Qi iptables-nft
  register: result
  ignore_errors: true
  changed_when: false
  when: ansible_distribution == 'Archlinux'

- name: Install iptables-nft
  shell: "yes y | pacman -S iptables-nft"
  args:
    executable: /bin/bash
  when: ansible_distribution == 'Archlinux' and result.rc != 0

- name: Reboot machine
  reboot:
  when: ansible_distribution == 'Archlinux' and result.rc != 0

- name: Install server packages (Arch)
  pacman:
    name: "{{ server_arch_packages }}"
    state: latest
  when: ansible_distribution == 'Archlinux'

- name: Install server packages (void)
  xbps:
    name: "{{ item }}"
    state: latest
  when: ansible_distribution == 'void'
  with_items: "{{ server_void_packages }}"

- name: Install pip packages
  pip:
    name: "{{ server_packages_pip }}"

- name: Setup services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker

- name: Add admin to group docker
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

