---
- name: iptables-nft is installed?
  command: pacman -Qi iptables-nft
  register: result
  ignore_errors: true
  changed_when: false

- name: Install iptables-nft
  shell: "yes y | pacman -S iptables-nft"
  args:
    executable: /bin/bash
  when: result.rc != 0

- name: Reboot machine
  reboot:
  when: result.rc != 0

- name: Install server package
  pacman:
    name: "{{ server_packages }}"
    state: latest

- name: Install pip packages
  pip:
    name: "{{ server_packages_pip }}"

- name: Setup services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker

- name: Add admin to group docker
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

