- name: Update keys
  shell: pacman-key --populate > ~/.pacman-key
  args:
    creates: ~/.pacman-key

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install required packages
  pacman:
    name: "{{ pacman_packages }}"
    state: latest

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    use: makepkg
    state: present   # TODO - latest
  become_user: "{{ admin_user }}"

- name: Update AUR packages
  kewlfft.aur.aur:
    upgrade: yes
    use: yay
    aur_only: yes
  become_user: "{{ admin_user }}"
