- name: Update keys
  shell: pacman-key --populate > ~/.pacman-key
  args:
    creates: ~/.pacman-key
  become: true

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install required packages
  pacman:
    name: [
      'unzip', 'sudo', 'vim', 'wget', 'iwd', 'dhcpcd', 'bash-completion', 'man-db',
      'man-pages', 'tmux', 'git', 'gcc', 'mlocate', 'dnsutils', 'htop', 'lsof',
      'inetutils', 'mc', 'base-devel', 'jq', 'tree', 'vi', 'ansible'
    ]
    state: latest
  become: true

- name: Install AUR packages
  kewlfft.aur.aur:
    name: [ 'aws-cli-v2-bin', 'yay-bin' ]
    use: makepkg
    state: present   # TODO - latest

- name: Update AUR packages
  kewlfft.aur.aur:
    upgrade: yes
    use: yay
    aur_only: yes
